### ISSUE TITLE
Pergunta

### ISSUE THREAD

**Issue by alexalannunes** [wendtecnologia/semver#11]
Nessa versão de correção x.y.0, devo incrementá-la de acordo com o número de bugs. Ex.: fiz 4 correções de bugs, ficaria x.y.4 ou incremento de acordo o dia que achei os bugs. Tipo: achei esses 4 em um dia => x.y.1 ??

**Comment by walkeralencar** [comment]
Sempre que há correçoes na X.Y.z, vc incrementa o Z, mas assim que o Y é incrementado, a contagem do Z é zerada tb.

**Comment by nunomazer** [comment]
@alexalannunes suponha que a versão é 1.1.0 ... você trabalha para resolver 4 bugs e então gera a nova versão, ela será 1.1.1, pois está lançando a nova versão apenas com resolução de bugs, não importa quantos. 

A explicação de @walkeralencar é uma complementação desta. Se estiver lançando uma nova versão com novas melhorias incrementa o Y e zera Z, por exemplo, 1.2.0

**Comment by alexalannunes** [comment]
@walkeralencar @nunomazer agora sim hehe vlws
