### ISSUE TITLE
Corrigir texto

### ISSUE THREAD

**Issue by israelss** [wendtecnologia/semver#9]
Há um espaço que deve ser removido entre _[RFC 2119]_ e  _(http://tools.ietf.org/html/rfc2119)_ no parágrafo único da seção **Especificação de Versionamento Semântico (SemVer)**, para que o link seja formatado corretamente, de acordo com a [sintaxe Markdown](https://guides.github.com/features/mastering-markdown/), ou seja, para que seja exibido assim: [RFC 2119](http://tools.ietf.org/html/rfc2119)

**Comment by reebr** [comment]
A correção foi enviada no PR: https://github.com/semver/semver.org/pull/232

**Comment by walkeralencar** [comment]
Ajuste do link, foi feito o merge.
Quanto ao PR no semver/semver sem a referencia de link referenciando o trabalho feito por varios profissionais colaborativamente, nao tem como concordar né...
